-- MySQL Script generated by MySQL Workbench
-- 09/26/16 14:07:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Atiende`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Atiende` (
  `idabogado` INT NOT NULL,
  `idcaso` VARCHAR(45) NOT NULL,
  `fecha_inicio` DATE NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idabogado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Abogado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Abogado` (
  `idabogado` INT NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `apellido` VARCHAR(20) NOT NULL,
  `cedula` VARCHAR(20) NULL,
  PRIMARY KEY (`idabogado`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC),
  CONSTRAINT `idabogado_atiende`
    FOREIGN KEY (`idabogado`)
    REFERENCES `mydb`.`Atiende` (`idabogado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Caso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Caso` (
  `idcaso` INT NOT NULL,
  `fecha_registro` DATE NULL,
  `descripcion` VARCHAR(45) NULL,
  `demandante` VARCHAR(45) NULL,
  `demandado` VARCHAR(45) NULL,
  PRIMARY KEY (`idcaso`),
  CONSTRAINT `caso_atiende`
    FOREIGN KEY (`idcaso`)
    REFERENCES `mydb`.`Atiende` (`idabogado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
