-- MySQL Script generated by MySQL Workbench
-- 03/26/17 21:24:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Enfermo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Enfermo` (
  `Incripcion` INT NOT NULL COMMENT '',
  `Apellido` VARCHAR(50) NULL COMMENT '',
  `Direccion` VARCHAR(50) NULL COMMENT '',
  `Fecha_Nac` VARCHAR(50) NULL COMMENT '',
  `S` VARCHAR(2) NULL COMMENT '',
  `NSS` INT NULL COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Plantilla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Plantilla` (
  `Sala_Cod` INT NOT NULL COMMENT '',
  `Hospital_Cod` INT NOT NULL COMMENT '',
  `Apellido` VARCHAR(50) NULL COMMENT '',
  `Fincion` VARCHAR(50) NULL COMMENT '',
  `T` VARCHAR(50) NULL COMMENT '',
  `Salario` VARCHAR(50) NULL COMMENT '',
  PRIMARY KEY (`Sala_Cod`, `Hospital_Cod`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sala` (
  `Sala_Cod` INT NOT NULL COMMENT '',
  `Hospital_Cod` INT NOT NULL COMMENT '',
  `Nombre` VARCHAR(50) NULL COMMENT '',
  `Num_Cama` INT NULL COMMENT '',
  PRIMARY KEY (`Sala_Cod`, `Hospital_Cod`)  COMMENT '',
  CONSTRAINT `tiene una plantilla`
    FOREIGN KEY (`Sala_Cod`)
    REFERENCES `mydb`.`Plantilla` (`Sala_Cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Doctor` (
  `Doctor_No` INT NOT NULL COMMENT '',
  `Hospital_Cod` INT NOT NULL COMMENT '',
  `Apellido` VARCHAR(50) NULL COMMENT '',
  `Especialidad` VARCHAR(50) NULL COMMENT '',
  PRIMARY KEY (`Doctor_No`, `Hospital_Cod`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hospital` (
  `Hospital_Cod` INT NOT NULL COMMENT '',
  `Nombre` VARCHAR(50) NULL COMMENT '',
  `Direccion` VARCHAR(50) NULL COMMENT '',
  `Telefono` VARCHAR(50) NULL COMMENT '',
  `Num_Cama` INT NULL COMMENT '',
  PRIMARY KEY (`Hospital_Cod`)  COMMENT '',
  CONSTRAINT `tiene una sala`
    FOREIGN KEY (`Hospital_Cod`)
    REFERENCES `mydb`.`Sala` (`Hospital_Cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tiene una doctor`
    FOREIGN KEY (`Hospital_Cod`)
    REFERENCES `mydb`.`Doctor` (`Hospital_Cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Emp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Emp` (
  `Emp_No` INT NOT NULL COMMENT '',
  `Dept_No` INT NOT NULL COMMENT '',
  `Apellido` VARCHAR(50) NULL COMMENT '',
  `Oficio` VARCHAR(50) NULL COMMENT '',
  `Dir` INT NULL COMMENT '',
  `Fecha_Alt` DATE NULL COMMENT '',
  `Salario` DECIMAL(9,2) NULL COMMENT '',
  `Comision` DECIMAL(9,2) NULL COMMENT '',
  PRIMARY KEY (`Emp_No`, `Dept_No`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dept`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dept` (
  `Dept_No` INT NOT NULL COMMENT '',
  `Nombre` VARCHAR(50) NULL COMMENT '',
  `Loc` VARCHAR(50) NULL COMMENT '',
  PRIMARY KEY (`Dept_No`)  COMMENT '',
  CONSTRAINT `empleado`
    FOREIGN KEY (`Dept_No`)
    REFERENCES `mydb`.`Emp` (`Dept_No`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
